app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::auth();

Route::get('/home', 'HomeController@index');

//add new
Route::get('auth/github', 'Auth\AuthController@redirectToGitHub');
Route::get('auth/github/callback', 'Auth\AuthController@handleGitHubCallback');

//Route::resource('project.task', 'ProjectTaskController');
Route::group(['middleware'=>'auth'], function(){
    Route::resource('project', 'ProjectController');
    Route::resource('project.task', 'ProjectTaskController');
    Route::resource('task', 'TaskController', ['only' => ['index', 'show',]]);
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name', 'description', ];

    public function tasks(){
        return $this->hasMany(Task::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Auth;
use App\Project;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $projects = Project::where('user_id', $user->id)->get();
        //dump($projects); die;
        return view('project.index')->with('projects', $projects);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $proj = new Project([
                            'name' => $request->get('name'),
                            'description' => $request->get('description'),
                            ]);
        $user = Auth::user();
        $proj->user()->associate($user->id);

        $proj->save();

        return redirect()->route('project.show', $proj->id)->with('message', '새로운 프로젝트가 생성되었습니다.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $proj = Project::find($id);
        if($proj == null){
            abort(404, $id. ' 모델을 찾을 수가 없습니다.');
        }

        return view('project.show')->withProj($proj);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $proj = Project::findOrFail($id);

        return view('project.edit')->with('proj', $proj);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $proj = Project::findOrFail($id);
        $proj->update([
                      'name'=>$request->get('name'),
                      'description'=>$request->get('description'),
                      ]);
        return redirect()->route('project.show', $proj->id)->with('message', $proj->name. ' 프로젝트가 수정 되었습니다.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $proj = Project::findOrFail($id);

        foreach ($proj->tasks()->get() as $task) {
            $task->delete();
        }

        $proj->delete();

        return redirect()->route('project.index')->with('message', $proj->name. ' 프로젝트가 삭제되었습니다.');
    }
}

resources/views/project/create.blade.php
@extends('layouts.app')

@section('title')
프로젝트 생성
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>프로젝트 생성</h1>
            <form class="form-horizontal" method="POST" action="{{ route('project.store') }}" role="form">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name">프로젝트 명</label>
                    <div>
                        <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="description">프로젝트 설명</label>
                    <div>
                        <textarea class="form-control" rows="5" name="description">{{ old('description') }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <button type="submit" class="btn btn-primary">프로젝트 생성</button>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>
@endsection

resources/views/project/edit.blade.php
@extends('layouts.app')

@section('title')
    프로젝트 수정
@endsection

@section('content')
    <div class="container">
    <div class="row">
    <div class="col-md-8">
        <form class="form-horizontal" role="form" method="POST" action="{{ route('project.update', $proj->id) }}">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            <div class="form-group">
                <label for="name">프로젝트 명</label>
                <div>
                    <input type="text" name="name" value="{{ $proj->name }}" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <label for="description">프로젝트 설명</label>
                <div>
                    <textarea name="description" class="form-control" rows="5">{{ $proj->description }}</textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="created_at">생성일</label>
                <div>
                    <input type="text" name="created_at" class="form-control" readonly="true" value="{{ $proj->created_at }}">
                </div>
            </div>

            <div class="form-group">
                <div>
                    <button class="btn btn-primary" type="submit">수정</button>
                </div>
            </div>

        </form>
    </div>
    </div>
    </div>



@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('title')
    프로젝트 목록
@endsection

@section('content')
<div class="container">
<div class="row">
    <div class="col-md-12">
        <p>
            <a href="{{ route('project.create') }}" class="btn btn-success">프로젝트생성</a>
        </p>

        @if(Session::has('message'))
            <div class="alert alert-info">{{ Session::get('message') }}</div>
        @endif

        <table class="table table-striped">
            <thead>
                <tr>
                    <td>이름</td>
                    <td>Description</td>
                    <td>생성일</td>
                </tr>
            </thead>
            <tbody>
                @foreach ($projects as $proj)
                    <tr>
                        <td>
                            <a href="{{ route('project.show', [$proj->id]) }}">{{ $proj->name }}</a>
                        </td>
                        <td>
                            {{ $proj->description }}
                        </td>
                        <td>
                            {{ $proj->created_at }}
                        </td>
                        <td>
                            <a href="{{ route('project.edit', $proj->id) }}" class="btn btn-success">편집</a>
                        </td>
                        <td>
                            <form method="POST" action="{{ route('project.destroy', $proj->id) }}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button class="btn btn-danger" type="submit">삭제</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>
</div>
@endsection

resources/views/project/show.blade.php
@extends('layouts.app')

@section('title')
    프로젝트 정보
@endsection

@section('content')
<div class="container">
<div class="row">
    <div class="col-md-8">
        @if(Session::has('message'))
            <div class="alert alert-info">{{ Session::get('message') }}</div>
        @endif
        <h3>프로젝트 정보</h3>
        <div class="form-group">
            <label for="name">프로젝트 명</label>
            <div>
                <input type="text" name="name" class="form-control" value="{{ $proj->name }}" readonly="true">
            </div>
        </div>

        <div class="form-group">
            <label for="description">설명</label>
            <div>
                <textarea class="form-control" rows="3" name="description"  readonly="true">{{ $proj->description }}</textarea>
            </div>
        </div>

        <div class="form-group">
            <label for="created_at">생성일</label>
            <div>
                <input type="text" name="created_at" class="form-control" value="{{ $proj->created_at }}" readonly="true">
            </div>
        </div>

        <div class="form-group">
            <label for="updated_at">수정일</label>
            <div>
                <input type="text" name="updated_at" class="form-control" value="{{ $proj->updated_at }}" readonly="true">
            </div>
        </div>

        <p>
            <a href="{{ route('project.task.index', $proj->id) }}" class="btn btn-info">Task 목록 보기</a>
        </p>

    </div>
</div>
</div>
@endsection