app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::auth();

Route::get('/home', 'HomeController@index');

//add new
Route::get('auth/github', 'Auth\AuthController@redirectToGitHub');
Route::get('auth/github/callback', 'Auth\AuthController@handleGitHubCallback');

//Route::resource('project.task', 'ProjectTaskController');
Route::group(['middleware'=>'auth'], function(){
    Route::resource('project', 'ProjectController');
    Route::resource('project.task', 'ProjectTaskController');
    Route::resource('task', 'TaskController', ['only' => ['index', 'show',]]);
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name', 'description', ];

    public function tasks(){
        return $this->hasMany(Task::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Task extends Model
{
    protected $fillable = ['name', 'description','due_date', 'priority', 'status'];

    protected $dates = ['due_date'];

    public function project(){
        return $this->belongsTo(Project::class);
    }

    public function scopDueDays($query, $days){
        $now = Carbon::now();
        return $query->where('due_date', '>', $now)->where('due_date', '<', $now->copy()->addDays($days));
    }

    public function scopeDueDateBetween($query, Carbon $start_date, Carbon $end_date){
        return $query->whereBetween('due_date', [$start_date->startOfDay(), $end_date->endOfDay()]);
    }

    public function scopeOtherParam($query, \Illuminate\Http\Request $request){
        $priority = $request->get('priority');
        if(!empty($priority) && $priority!= 'all'){
            $query = $query->where('priority', $priority);
        }

        $status = $request->get('status');
        if(!empty($status) && $status!= 'all'){
            $query = $query->where('status', $status);
        }

        return $query;
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Auth;
use App\Project;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $projects = Project::where('user_id', $user->id)->get();
        //dump($projects); die;
        return view('project.index')->with('projects', $projects);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $proj = new Project([
                            'name' => $request->get('name'),
                            'description' => $request->get('description'),
                            ]);
        $user = Auth::user();
        $proj->user()->associate($user->id);

        $proj->save();

        return redirect()->route('project.show', $proj->id)->with('message', '새로운 프로젝트가 생성되었습니다.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $proj = Project::find($id);
        if($proj == null){
            abort(404, $id. ' 모델을 찾을 수가 없습니다.');
        }

        return view('project.show')->withProj($proj);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $proj = Project::findOrFail($id);

        return view('project.edit')->with('proj', $proj);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $proj = Project::findOrFail($id);
        $proj->update([
                      'name'=>$request->get('name'),
                      'description'=>$request->get('description'),
                      ]);
        return redirect()->route('project.show', $proj->id)->with('message', $proj->name. ' 프로젝트가 수정 되었습니다.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $proj = Project::findOrFail($id);

        foreach ($proj->tasks()->get() as $task) {
            $task->delete();
        }

        $proj->delete();

        return redirect()->route('project.index')->with('message', $proj->name. ' 프로젝트가 삭제되었습니다.');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Auth;
use Carbon\Carbon;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();

        if(!empty($request->get('start_date'))){
            $start_date = Carbon::createFromFormat('Y-m-d H:i:s', $request->get('start_date'));
        } else {
            $start_date = Carbon::now();
        }

        if(!empty($request->get('end_date'))){
            $end_date = Carbon::createFromFormat('Y-m-d H:i:s', $request->get('end_date'));
        } else {
            $end_date = $start_date->copy()->addMonths(1);
        }

        //$start_date = Carbon::now();
        //$end_date = $start_date->copy()->addMonths(1);

        $tasks = $user->tasks()
                ->dueDateBetween($start_date, $end_date)
                ->otherParam($request)
                ->orderBy('due_date', 'desc')->get();

        return view('task.index')
            ->with('tasks', $tasks)
            ->with('start_date', $start_date)
            ->with('end_date', $end_date)
            ->with('status', $request->get('status'))
            ->with('priority', $request->get('priority'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/project/task/create.blade.php
@extends('layouts.app')

@section('title')
    태스크 생성
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if(count($errors) > 0 )
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors as $e)
                            <li>{{ $e }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form class="form-horizontal" role="form" method="POST" action="{{ route('project.task.store', [$proj->id]) }}">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="name">태스크 명</label>
                    <div>
                        <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="description">설명</label>
                    <div>
                        <textarea class="form-control" rows="3" name="description">{{ old('description') }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label for="priority">우선순위</label>
                    <div>
                        <select class="form-control" name="priority">
                            @foreach (['low', 'medium', 'high'] as $p)
                                <option value="{{ $p }}" {{ (old('priority') === $p) ? "selected" : "" }}>{{ $p }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="status">상태</label>
                    <div>
                        <select class="form-control" name="status">
                            @foreach (['set', 'doing', 'done'] as $s)
                                <option value="{{ $s }}" {{ (old('status') === $s) ? "selected" : "" }}>{{ $s }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="due_date">기한</label>
                    <div class="input-group date" id="due_date">
                        <input type="text" name="due_date" class="form-control">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <button type="submit" class="btn btn-primary">생성</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    $(function(){
        $('#due_date').datetimepicker({
            locale:'en',
            defaultDate:{!! (old('due_date')) ? old('due_date') : "'". (Carbon\Carbon::now())."'" !!},
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
@endsection

resources/views/project/task/edit.blade.php
@extends('layouts.app')

@section('title')
    태스크 수정
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <form class="form-horizontal" role="form" method="POST" action="{{ route('project.task.update', [$task->project->id, $task->id]) }}">
                    {{ method_field('PUT') }}
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label for="project_id">프로젝트 선택</label>
                        <div>
                            <select class="form-control" name="project_id">
                                @foreach ($projects as $proj)
                                    <option value="{{ $proj->id }}" {{ ($task->project->id == $proj->id) ? "selected" : "" }}>{{ $proj->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name">태스크 명</label>
                        <div>
                            <input type="text" name="name" value="{{ $task->name }}" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="description">설명</label>
                        <div>
                            <textarea class="form-control" rows="3" name="description">{{ $task->description }}</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="priority">우선순위</label>
                        <div>
                            <select class="form-control" name="priority">
                                @foreach (['low', 'medium', 'high'] as $p)
                                    <option value="{{ $p }}" {{ ($task->priority === $p) ? "selected" : "" }}>{{ $p }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="status">상태</label>
                        <div>
                            <select name="status" class="form-control">
                                @foreach (['set', 'doing', 'done'] as $s)
                                    <option value="{{ $s }}" {{ ($task->status === $s) ? "selected" : "" }}>{{ $s }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="due_date">기한</label>
                        <div class="input-group date" id="due_date">
                            <input type="text" class="form-control" name="due_date" value="{{ $task->due_date }}">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="created_at">생성일</label>
                        <div>
                            <input type="text" name="created_at" class="form-control" value="{{ $task->created_at }}" readonly="true">
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <button type="submit" class="btn btn-primary">수정</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript">
        $(function(){
            $("#due_date").datetimepicker({
                locale:'en',
                defaultDate:'{{ $task->due_date }}',
                format: 'YYYY-MM-D HH:mm:ss'
            });
        });
    </script>
@endsection

resources/views/project/task/index.blade.php
@extends('layouts.app')

@section('title')
태스크 목록
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>{{ $proj->name }}</h3>
            <p>
                <a href="{{ route('project.task.create', $proj->id) }}" class="btn btn-success">Task 생성</a>
            </p>
            @if(Session::has('message'))
                <div class="alert alert-info">
                    {{ Session::get('message') }}
                </div>
            @endif

            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>이름</td>
                        <td>우선순위</td>
                        <td>상태</td>
                        <td>기한</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($tasks as $task)
                        <tr>
                            <td>
                                <a href="{{ route('project.task.show',[$proj->id, $task->id]) }}">{{ $task->name }}</a>
                            </td>
                            <td>
                                {{ $task->priority }}
                            </td>
                            <td>
                                {{ $task->status }}
                            </td>
                            <td>
                                {{ $task->due_date }}
                            </td>
                            <td>
                                <a href="{{ route('project.task.edit', [$proj->id, $task->id]) }}" class="btn btn-success">편집</a>
                            </td>
                            <td>
                                <form method="POST" action="{{ route('project.task.destroy', [$proj->id, $task->id]) }}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-danger">삭제</button>

                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection